# This will set the replicaset count, more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

gitPages:
  config: |
    # This is a configuration used for demonstration purposes.
    # See: https://git-pages.org/running-a-server/#configuration

    log-format = "text"

    [server]
    # Use "-" to disable the handler.
    pages = "tcp/0.0.0.0:3000"
    caddy = "-"
    metrics = "tcp/0.0.0.0:3002"

    [[wildcard]] # non-default section
    domain = "codeberg.page"
    clone-url = "https://codeberg.org/<user>/<project>.git"
    index-repo = "pages"
    index-repo-branch = "main"
    authorization = "forgejo"

    [fallback] # non-default section
    proxy-to = "https://codeberg.page"
    insecure = false

    [storage]
    type = "fs"

    [storage.fs]
    root = "/data"

    [limits]
    max-site-size = "128M"
    max-manifest-size = "1M"
    max-inline-file-size = "256B"
    git-large-object-threshold = "1M"
    max-symlink-depth = 16
    update-timeout = "60s"
    concurrent-uploads = 1024
    max-heap-size-ratio = 0.5 # * RAM_size
    forbidden-domains = []
    allowed-repository-url-prefixes = []
    allowed-custom-headers = ["X-Clacks-Overhead"]
    allow-basic-auth = false

    [audit]
    node-id = 0
    collect = false
    include-ip = ""
    notify-url = ""

    [observability]
    slow-response-threshold = "500ms"

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: codeberg.org/git-pages/git-pages
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# Persistent storage configuration for deployed sites
persistence:
  enabled: true
  # storageClassName: "standard"
  size: 10Gi
  mountPath: /data

serviceMonitor:
  enabled: false
  namespace: ""
  interval: 30s
  scrapeTimeout: 10s

# This section builds out the service account, more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created.
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account.
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template.
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information check out: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information check out: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# This is for setting up a service, more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type, more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports, more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 3000
  caddyPort: 3001
  metricsPort: 3002

# This block is for setting up the ingress, more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: git-pages.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
    # - secretName: git-pages-tls
    #   hosts:
    #     - git-pages.local

# -- Expose the service via gateway-api HTTPRoute
# Requires Gateway API resources and suitable controller installed within the cluster
# (see: https://gateway-api.sigs.k8s.io/guides/)
httpRoute:
  # HTTPRoute enabled.
  enabled: false
  # HTTPRoute annotations.
  annotations: {}
  # Which Gateways this Route is attached to.
  parentRefs:
    - name: gateway
      sectionName: http
      # namespace: default
  # Hostnames matching HTTP header.
  hostnames:
    - git-pages.local
  # List of rules and filters applied.
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /headers
  #   filters:
  #   - type: RequestHeaderModifier
  #     requestHeaderModifier:
  #       set:
  #       - name: My-Overwrite-Header
  #         value: this-is-the-only-value
  #       remove:
  #       - User-Agent
  # - matches:
  #   - path:
  #       type: PathPrefix
  #       value: /echo
  #     headers:
  #     - name: version
  #       value: v2

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# This is to setup the liveness and readiness probes, more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  tcpSocket:
    port: http
readinessProbe:
  tcpSocket:
    port: http

# This section is for setting up autoscaling, more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
  # - name: foo
  #   secret:
  #     secretName: mysecret
  #     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
  # - name: foo
  #   mountPath: "/etc/foo"
  #   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
