apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "git-pages.fullname" . }}-config
  labels:
    {{- include "git-pages.labels" . | nindent 4 }}
data:
  config.toml: |
    {{- .Values.gitPages.config | nindent 4 }}
